# Generated by Django 3.0.5 on 2020-12-12 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
            ],
        ),
    ]
