# Generated by Django 3.0.5 on 2020-12-13 00:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201212_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='city',
        ),
        migrations.AddField(
            model_name='signal',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0], size=2),
        ),
    ]
